// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieSystem.DataAccess;

#nullable disable

namespace MovieSystemAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230420091503_UniqueConstraint")]
    partial class UniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieSystem.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 28,
                            Description = "Big BOOM",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Big ADVENTURE",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Big COMPUTERGRAPHIC",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Big LAUGH",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 80,
                            Description = "Big POLICE CHASE",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 99,
                            Description = "Big REAL LIFE MOVIE",
                            Name = "Documentary"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Big ARGUMENT",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 10751,
                            Description = "Vin Diesel",
                            Name = "Family"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Big NERD",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Big OLD MAN STORY",
                            Name = "History"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Big SCARE",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10402,
                            Description = "Big UNTZ UNTZ",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 9648,
                            Description = "Big HMM",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 10749,
                            Description = "Big LOVE STORY",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 878,
                            Description = "Big SMARTS",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 10770,
                            Description = "Big MOVIE",
                            Name = "TV Movie"
                        },
                        new
                        {
                            Id = 53,
                            Description = "Big MICHAEL JACKSON",
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 10752,
                            Description = "Big PANG PANG",
                            Name = "War"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Big YEHAAAW",
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("MovieSystem.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("date");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieSystem.Models.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId", "GenreId")
                        .IsUnique();

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("MovieSystem.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MovieSystem.Models.PersonGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("PersonId", "GenreId")
                        .IsUnique();

                    b.ToTable("PersonGenres");
                });

            modelBuilder.Entity("MovieSystem.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("MovieRating")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("PersonId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("MovieSystem.Models.Movie", b =>
                {
                    b.HasOne("MovieSystem.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieSystem.Models.MovieGenre", b =>
                {
                    b.HasOne("MovieSystem.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieSystem.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieSystem.Models.PersonGenre", b =>
                {
                    b.HasOne("MovieSystem.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieSystem.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MovieSystem.Models.Rating", b =>
                {
                    b.HasOne("MovieSystem.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieSystem.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
